enchantmentIDs:
    Protection: 0
    Fire Protection: 1
    Feather Falling: 2
    Blast Protection: 3
    Projectile Protection: 4
    Respiration: 5
    Aqua Affinity: 6
    Sharpness: 16
    Smite: 17
    Bane of Arthropods: 18
    Knockback: 19
    Fire Aspect: 20
    Looting: 21
    Efficiency: 32
    Silk Touch: 33
    Unbreaking: 34
    Fortune: 35
    Power: 48
    Punch: 49
    Flame: 50
    Infinity: 51
items:
    Pickaxe:
    - diamond_pickaxe
    - gold_pickaxe
    - iron_pickaxe
    - stone_pickaxe
    - wood_pickaxe
    # Add your RP2 Ruby, Sapphire, Emerald or IC2 bronze tools here (item IDs)..
    Hoe:
    - diamond_hoe
    - gold_hoe 
    - iron_hoe
    - stone_hoe
    - wood_hoe
    Sword:
    - diamond_sword   
    - gold_sword
    - iron_sword
    - stone_sword
    - wood_sword
    Shovel:
    - diamond_spade
    - gold_spade
    - iron_spade
    - stone_spade
    - wood_spade
    Axe:
    - diamond_axe
    - gold_axe
    - iron_axe
    - stone_axe
    - wood_axe
    # Farm-related block, either land or growing crops 
    Farmblock:
    - soil      # Farmland
    - crops     # Wheat TODO: update wiki, calls 'Wheat Seeds' though in-game 'Crops'
    - sugar_cane_block
    - cake_block
    - pumpkin_stem
    - melon_stem
    - nether_warts # Not the item, that is nether_stalk (confusingly)
    # Able to be excavated by shovel
    Excavatable:
    - dirt
    - grass
    - gravel
    #- sand
    - soul_sand
    - netherrack  # Not normally diggable, but why not?
    WoodenBlock:
    - wood
    - wood_plate
    - wood_stairs
    - wooden_door
    - log
    - step;2            # wooden slab
    - double_step;2     # wooden double slab

effects:
    Bow + Feather Falling:
        enable: true
    Bow + Respiration:
        enable: false

moveListener: true
