name: EnchantMore
main: me.exphc.EnchantMore.EnchantMore
version: 0.5.1a
website: http://dev.bukkit.org/server-mods/enchantmore/
description: enchanted hoes, enchanted fishing rods, enchanted shears and more!

